Travis: don't run against PHPCS 2.0.0 or 2.1.0
We are incompatible with 2.0.0:

```
Fatal error: Call to undefined method
PHP_CodeSniffer_File::findEndOfStatement() in
/home/travis/build/WordPress-Coding-Standards/WordPress-Coding-Standards
/WordPress/Sniffs/XSS/EscapeOutputSniff.php on line 347
```

We can run against 2.1.0, however, there are some oddities, possibly in
the parser or something, that cause the tests for
`WordPress.XSS.EscapeOutput` to fail.

Fo more details you can see the travis build:
https://travis-ci.org/WordPress-Coding-Standards/WordPress-Coding-Standa
rds/builds/63017423